version: '3'

services:
  backend:
    image: kiranmohanm/projectmanagamentbackend
    ports:
      - 3031:3031
  
  frontend:
    image: kiranmohanm/projectmanagamentfrontend
    ports:
      - 80:80
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=3031
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
